image: node:18.20.0-alpine

stages:
  - build

build:
  stage: build
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn-cache/
    policy: pull
  before_script:
    - echo 'yarn-offline-mirror ".yarn-cache/"' >> .yarnrc
    - echo 'yarn-offline-mirror-pruning true' >> .yarnrc
    - yarn install --frozen-lockfile
    - yarn cache clean
    - rm -rf node_modules/.cache
  script:
    - yarn build
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

pages:
  stage: build
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn-cache/
    policy: pull
  before_script:
    - echo 'yarn-offline-mirror ".yarn-cache/"' >> .yarnrc
    - echo 'yarn-offline-mirror-pruning true' >> .yarnrc
    - yarn install --frozen-lockfile
    - yarn cache clean
    - rm -rf node_modules/.cache
  script:
    - yarn build
    - cp -a dist/. public/
    - echo '/* /index.html 200' > public/_redirects
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH